steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - $_IMAGE
      - --build-arg
      - VITE_SUPABASE_URL=$_VITE_SUPABASE_URL
      - --build-arg
      - VITE_SUPABASE_ANON_KEY=$_VITE_SUPABASE_ANON_KEY
      - --build-arg
      - VITE_SUPABASE_REDIRECT_URL=$_VITE_SUPABASE_REDIRECT_URL
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_IMAGE

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE
      - --image
      - $_IMAGE
      - --region
      - $_REGION
      - --platform
      - managed
      - --allow-unauthenticated

images:
  - $_IMAGE

substitutions:
  _REGION: us-west1
  _SERVICE: coastercount-pro
  _IMAGE: us-west1-docker.pkg.dev/gen-lang-client-0691213576/coastercount/coastercount-pro:latest
  _VITE_SUPABASE_URL: ""
  _VITE_SUPABASE_ANON_KEY: ""
  _VITE_SUPABASE_REDIRECT_URL: ""
options:
  logging: CLOUD_LOGGING_ONLY
