import { Coaster, CoasterType, User } from './types';

// A curated list of top roller coasters worldwide to simulate a large database
export const INITIAL_COASTERS: Coaster[] = [
  // --- USA: CEDAR POINT ---
  { id: 'cp1', name: 'Steel Vengeance', park: 'Cedar Point', country: 'USA', type: CoasterType.Hybrid, manufacturer: 'RMC', imageUrl: 'https://picsum.photos/800/600?random=1' },
  { id: 'cp2', name: 'Millennium Force', park: 'Cedar Point', country: 'USA', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=2' },
  { id: 'cp3', name: 'Maverick', park: 'Cedar Point', country: 'USA', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=3' },
  { id: 'cp4', name: 'Top Thrill 2', park: 'Cedar Point', country: 'USA', type: CoasterType.Steel, manufacturer: 'Zamperla', imageUrl: 'https://picsum.photos/800/600?random=4' },
  { id: 'cp5', name: 'Magnum XL-200', park: 'Cedar Point', country: 'USA', type: CoasterType.Steel, manufacturer: 'Arrow', imageUrl: 'https://picsum.photos/800/600?random=5' },
  { id: 'cp6', name: 'GateKeeper', park: 'Cedar Point', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=6' },
  { id: 'cp7', name: 'Valravn', park: 'Cedar Point', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=7' },
  { id: 'cp8', name: 'Raptor', park: 'Cedar Point', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=8' },
  { id: 'cp9', name: 'Gemini', park: 'Cedar Point', country: 'USA', type: CoasterType.Hybrid, manufacturer: 'Arrow', imageUrl: 'https://picsum.photos/800/600?random=9' },
  { id: 'cp10', name: 'Rougarou', park: 'Cedar Point', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=10' },

  // --- USA: SIX FLAGS MAGIC MOUNTAIN ---
  { id: 'sfmm1', name: 'X2', park: 'Six Flags Magic Mountain', country: 'USA', type: CoasterType.Steel, manufacturer: 'Arrow', imageUrl: 'https://picsum.photos/800/600?random=11' },
  { id: 'sfmm2', name: 'Twisted Colossus', park: 'Six Flags Magic Mountain', country: 'USA', type: CoasterType.Hybrid, manufacturer: 'RMC', imageUrl: 'https://picsum.photos/800/600?random=12' },
  { id: 'sfmm3', name: 'Tatsu', park: 'Six Flags Magic Mountain', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=13' },
  { id: 'sfmm4', name: 'Full Throttle', park: 'Six Flags Magic Mountain', country: 'USA', type: CoasterType.Steel, manufacturer: 'Premier Rides', imageUrl: 'https://picsum.photos/800/600?random=14' },
  { id: 'sfmm5', name: 'West Coast Racers', park: 'Six Flags Magic Mountain', country: 'USA', type: CoasterType.Steel, manufacturer: 'Premier Rides', imageUrl: 'https://picsum.photos/800/600?random=15' },
  { id: 'sfmm6', name: 'Goliath', park: 'Six Flags Magic Mountain', country: 'USA', type: CoasterType.Steel, manufacturer: 'Giovanola', imageUrl: 'https://picsum.photos/800/600?random=16' },
  { id: 'sfmm7', name: 'Wonder Woman Flight of Courage', park: 'Six Flags Magic Mountain', country: 'USA', type: CoasterType.Steel, manufacturer: 'RMC', imageUrl: 'https://picsum.photos/800/600?random=17' },
  { id: 'sfmm8', name: 'Viper', park: 'Six Flags Magic Mountain', country: 'USA', type: CoasterType.Steel, manufacturer: 'Arrow', imageUrl: 'https://picsum.photos/800/600?random=18' },

  // --- USA: SIX FLAGS GREAT ADVENTURE ---
  { id: 'sfga1', name: 'El Toro', park: 'Six Flags Great Adventure', country: 'USA', type: CoasterType.Wooden, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=19' },
  { id: 'sfga2', name: 'Kingda Ka', park: 'Six Flags Great Adventure', country: 'USA', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=20' },
  { id: 'sfga3', name: 'Nitro', park: 'Six Flags Great Adventure', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=21' },
  { id: 'sfga4', name: 'Jersey Devil Coaster', park: 'Six Flags Great Adventure', country: 'USA', type: CoasterType.Steel, manufacturer: 'RMC', imageUrl: 'https://picsum.photos/800/600?random=22' },

  // --- USA: FLORIDA PARKS ---
  { id: 'fl1', name: 'Iron Gwazi', park: 'Busch Gardens Tampa', country: 'USA', type: CoasterType.Hybrid, manufacturer: 'RMC', imageUrl: 'https://picsum.photos/800/600?random=23' },
  { id: 'fl2', name: 'VelociCoaster', park: 'Islands of Adventure', country: 'USA', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=24' },
  { id: 'fl3', name: 'Mako', park: 'SeaWorld Orlando', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=25' },
  { id: 'fl4', name: 'Montu', park: 'Busch Gardens Tampa', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=26' },
  { id: 'fl5', name: 'Kumba', park: 'Busch Gardens Tampa', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=27' },
  { id: 'fl6', name: 'Cheetah Hunt', park: 'Busch Gardens Tampa', country: 'USA', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=28' },
  { id: 'fl7', name: 'Hagrid\'s Magical Creatures Motorbike Adventure', park: 'Islands of Adventure', country: 'USA', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=29' },
  { id: 'fl8', name: 'Incredible Hulk', park: 'Islands of Adventure', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=30' },
  { id: 'fl9', name: 'Guardians of the Galaxy: Cosmic Rewind', park: 'Epcot', country: 'USA', type: CoasterType.Steel, manufacturer: 'Vekoma', imageUrl: 'https://picsum.photos/800/600?random=31' },
  { id: 'fl10', name: 'Tron Lightcycle / Run', park: 'Magic Kingdom', country: 'USA', type: CoasterType.Steel, manufacturer: 'Vekoma', imageUrl: 'https://picsum.photos/800/600?random=32' },
  { id: 'fl11', name: 'Kraken', park: 'SeaWorld Orlando', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=33' },
  { id: 'fl12', name: 'Pipeline', park: 'SeaWorld Orlando', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=34' },

  // --- USA: OTHER MAJOR PARKS ---
  { id: 'usa1', name: 'Fury 325', park: 'Carowinds', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=35' },
  { id: 'usa2', name: 'Intimidator 305', park: 'Kings Dominion', country: 'USA', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=36' },
  { id: 'usa3', name: 'Twisted Timbers', park: 'Kings Dominion', country: 'USA', type: CoasterType.Hybrid, manufacturer: 'RMC', imageUrl: 'https://picsum.photos/800/600?random=37' },
  { id: 'usa4', name: 'Skyrush', park: 'Hersheypark', country: 'USA', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=38' },
  { id: 'usa5', name: 'Wildcat\'s Revenge', park: 'Hersheypark', country: 'USA', type: CoasterType.Hybrid, manufacturer: 'RMC', imageUrl: 'https://picsum.photos/800/600?random=39' },
  { id: 'usa6', name: 'Candymonium', park: 'Hersheypark', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=40' },
  { id: 'usa7', name: 'Lightning Rod', park: 'Dollywood', country: 'USA', type: CoasterType.Wooden, manufacturer: 'RMC', imageUrl: 'https://picsum.photos/800/600?random=41' },
  { id: 'usa8', name: 'Thunderhead', park: 'Dollywood', country: 'USA', type: CoasterType.Wooden, manufacturer: 'GCI', imageUrl: 'https://picsum.photos/800/600?random=42' },
  { id: 'usa9', name: 'Time Traveler', park: 'Silver Dollar City', country: 'USA', type: CoasterType.Steel, manufacturer: 'Mack', imageUrl: 'https://picsum.photos/800/600?random=43' },
  { id: 'usa10', name: 'Outlaw Run', park: 'Silver Dollar City', country: 'USA', type: CoasterType.Wooden, manufacturer: 'RMC', imageUrl: 'https://picsum.photos/800/600?random=44' },
  { id: 'usa11', name: 'The Voyage', park: 'Holiday World', country: 'USA', type: CoasterType.Wooden, manufacturer: 'Gravity Group', imageUrl: 'https://picsum.photos/800/600?random=45' },
  { id: 'usa12', name: 'Mystic Timbers', park: 'Kings Island', country: 'USA', type: CoasterType.Wooden, manufacturer: 'GCI', imageUrl: 'https://picsum.photos/800/600?random=46' },
  { id: 'usa13', name: 'Orion', park: 'Kings Island', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=47' },
  { id: 'usa14', name: 'Diamondback', park: 'Kings Island', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=48' },
  { id: 'usa15', name: 'The Beast', park: 'Kings Island', country: 'USA', type: CoasterType.Wooden, manufacturer: 'Kings Island', imageUrl: 'https://picsum.photos/800/600?random=49' },
  { id: 'usa16', name: 'GhostRider', park: 'Knott\'s Berry Farm', country: 'USA', type: CoasterType.Wooden, manufacturer: 'CCI', imageUrl: 'https://picsum.photos/800/600?random=50' },
  { id: 'usa17', name: 'Xcelerator', park: 'Knott\'s Berry Farm', country: 'USA', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=51' },
  { id: 'usa18', name: 'RailBlazer', park: 'California\'s Great America', country: 'USA', type: CoasterType.Steel, manufacturer: 'RMC', imageUrl: 'https://picsum.photos/800/600?random=52' },
  { id: 'usa19', name: 'Gold Striker', park: 'California\'s Great America', country: 'USA', type: CoasterType.Wooden, manufacturer: 'GCI', imageUrl: 'https://picsum.photos/800/600?random=53' },
  { id: 'usa20', name: 'Phoenix', park: 'Knoebels', country: 'USA', type: CoasterType.Wooden, manufacturer: 'PTC', imageUrl: 'https://picsum.photos/800/600?random=54' },
  { id: 'usa21', name: 'Phantom\'s Revenge', park: 'Kennywood', country: 'USA', type: CoasterType.Steel, manufacturer: 'Morgan', imageUrl: 'https://picsum.photos/800/600?random=55' },
  { id: 'usa22', name: 'Steel Curtain', park: 'Kennywood', country: 'USA', type: CoasterType.Steel, manufacturer: 'S&S', imageUrl: 'https://picsum.photos/800/600?random=56' },
  { id: 'usa23', name: 'Superman the Ride', park: 'Six Flags New England', country: 'USA', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=57' },
  { id: 'usa24', name: 'Wicked Cyclone', park: 'Six Flags New England', country: 'USA', type: CoasterType.Hybrid, manufacturer: 'RMC', imageUrl: 'https://picsum.photos/800/600?random=58' },
  { id: 'usa25', name: 'Storm Chaser', park: 'Kentucky Kingdom', country: 'USA', type: CoasterType.Steel, manufacturer: 'RMC', imageUrl: 'https://picsum.photos/800/600?random=59' },
  { id: 'usa26', name: 'Arieforce One', park: 'Fun Spot America Atlanta', country: 'USA', type: CoasterType.Steel, manufacturer: 'RMC', imageUrl: 'https://picsum.photos/800/600?random=60' },
  { id: 'usa27', name: 'Iron Rattler', park: 'Six Flags Fiesta Texas', country: 'USA', type: CoasterType.Hybrid, manufacturer: 'RMC', imageUrl: 'https://picsum.photos/800/600?random=61' },
  { id: 'usa28', name: 'Texas Stingray', park: 'SeaWorld San Antonio', country: 'USA', type: CoasterType.Wooden, manufacturer: 'GCI', imageUrl: 'https://picsum.photos/800/600?random=62' },
  { id: 'usa29', name: 'Cannibal', park: 'Lagoon', country: 'USA', type: CoasterType.Steel, manufacturer: 'Lagoon', imageUrl: 'https://picsum.photos/800/600?random=63' },
  { id: 'usa30', name: 'Afterburn', park: 'Carowinds', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=64' },
  { id: 'usa31', name: 'Copperhead Strike', park: 'Carowinds', country: 'USA', type: CoasterType.Steel, manufacturer: 'Mack', imageUrl: 'https://picsum.photos/800/600?random=65' },
  { id: 'usa32', name: 'Goliath', park: 'Six Flags Over Georgia', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=66' },
  { id: 'usa33', name: 'Twisted Cyclone', park: 'Six Flags Over Georgia', country: 'USA', type: CoasterType.Hybrid, manufacturer: 'RMC', imageUrl: 'https://picsum.photos/800/600?random=67' },
  { id: 'usa34', name: 'New Texas Giant', park: 'Six Flags Over Texas', country: 'USA', type: CoasterType.Hybrid, manufacturer: 'RMC', imageUrl: 'https://picsum.photos/800/600?random=68' },
  { id: 'usa35', name: 'Mr. Freeze Reverse Blast', park: 'Six Flags Over Texas', country: 'USA', type: CoasterType.Steel, manufacturer: 'Premier Rides', imageUrl: 'https://picsum.photos/800/600?random=69' },
  { id: 'usa36', name: 'Pantheon', park: 'Busch Gardens Williamsburg', country: 'USA', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=70' },
  { id: 'usa37', name: 'Apollo\'s Chariot', park: 'Busch Gardens Williamsburg', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=71' },
  { id: 'usa38', name: 'Alpengeist', park: 'Busch Gardens Williamsburg', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=72' },
  { id: 'usa39', name: 'Griffon', park: 'Busch Gardens Williamsburg', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=73' },

  // --- CANADA ---
  { id: 'can1', name: 'Leviathan', park: 'Canada\'s Wonderland', country: 'Canada', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=74' },
  { id: 'can2', name: 'Behemoth', park: 'Canada\'s Wonderland', country: 'Canada', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=75' },
  { id: 'can3', name: 'Yukon Striker', park: 'Canada\'s Wonderland', country: 'Canada', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=76' },
  { id: 'can4', name: 'Vortex', park: 'Canada\'s Wonderland', country: 'Canada', type: CoasterType.Steel, manufacturer: 'Arrow', imageUrl: 'https://picsum.photos/800/600?random=77' },

  // --- EUROPE: GERMANY ---
  { id: 'de1', name: 'Taron', park: 'Phantasialand', country: 'Germany', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=78' },
  { id: 'de2', name: 'F.L.Y.', park: 'Phantasialand', country: 'Germany', type: CoasterType.Steel, manufacturer: 'Vekoma', imageUrl: 'https://picsum.photos/800/600?random=79' },
  { id: 'de3', name: 'Black Mamba', park: 'Phantasialand', country: 'Germany', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=80' },
  { id: 'de4', name: 'Silver Star', park: 'Europa-Park', country: 'Germany', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=81' },
  { id: 'de5', name: 'Blue Fire', park: 'Europa-Park', country: 'Germany', type: CoasterType.Steel, manufacturer: 'Mack', imageUrl: 'https://picsum.photos/800/600?random=82' },
  { id: 'de6', name: 'Wodan Timbur Coaster', park: 'Europa-Park', country: 'Germany', type: CoasterType.Wooden, manufacturer: 'GCI', imageUrl: 'https://picsum.photos/800/600?random=83' },
  { id: 'de7', name: 'Expedition GeForce', park: 'Holiday Park', country: 'Germany', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=84' },
  { id: 'de8', name: 'Kärnan', park: 'Hansa-Park', country: 'Germany', type: CoasterType.Steel, manufacturer: 'Gerstlauer', imageUrl: 'https://picsum.photos/800/600?random=85' },
  { id: 'de9', name: 'Colossos - Kampf der Giganten', park: 'Heide Park', country: 'Germany', type: CoasterType.Wooden, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=86' },
  { id: 'de10', name: 'Flug der Dämonen', park: 'Heide Park', country: 'Germany', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=87' },

  // --- EUROPE: UK ---
  { id: 'uk1', name: 'Nemesis Reborn', park: 'Alton Towers', country: 'UK', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=88' },
  { id: 'uk2', name: 'The Smiler', park: 'Alton Towers', country: 'UK', type: CoasterType.Steel, manufacturer: 'Gerstlauer', imageUrl: 'https://picsum.photos/800/600?random=89' },
  { id: 'uk3', name: 'Wicker Man', park: 'Alton Towers', country: 'UK', type: CoasterType.Wooden, manufacturer: 'GCI', imageUrl: 'https://picsum.photos/800/600?random=90' },
  { id: 'uk4', name: 'Oblivion', park: 'Alton Towers', country: 'UK', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=91' },
  { id: 'uk5', name: 'Hyperia', park: 'Thorpe Park', country: 'UK', type: CoasterType.Steel, manufacturer: 'Mack', imageUrl: 'https://picsum.photos/800/600?random=92' },
  { id: 'uk6', name: 'Stealth', park: 'Thorpe Park', country: 'UK', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=93' },
  { id: 'uk7', name: 'The Swarm', park: 'Thorpe Park', country: 'UK', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=94' },
  { id: 'uk8', name: 'Saw - The Ride', park: 'Thorpe Park', country: 'UK', type: CoasterType.Steel, manufacturer: 'Gerstlauer', imageUrl: 'https://picsum.photos/800/600?random=95' },
  { id: 'uk9', name: 'Icon', park: 'Blackpool Pleasure Beach', country: 'UK', type: CoasterType.Steel, manufacturer: 'Mack', imageUrl: 'https://picsum.photos/800/600?random=96' },
  { id: 'uk10', name: 'The Big One', park: 'Blackpool Pleasure Beach', country: 'UK', type: CoasterType.Steel, manufacturer: 'Arrow', imageUrl: 'https://picsum.photos/800/600?random=97' },

  // --- EUROPE: POLAND ---
  { id: 'pl1', name: 'Zadra', park: 'Energylandia', country: 'Poland', type: CoasterType.Hybrid, manufacturer: 'RMC', imageUrl: 'https://picsum.photos/800/600?random=98' },
  { id: 'pl2', name: 'Hyperion', park: 'Energylandia', country: 'Poland', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=99' },
  { id: 'pl3', name: 'Abyssus', park: 'Energylandia', country: 'Poland', type: CoasterType.Steel, manufacturer: 'Vekoma', imageUrl: 'https://picsum.photos/800/600?random=100' },
  { id: 'pl4', name: 'Lech Coaster', park: 'Legendia', country: 'Poland', type: CoasterType.Steel, manufacturer: 'Vekoma', imageUrl: 'https://picsum.photos/800/600?random=101' },

  // --- EUROPE: BENELUX & FRANCE ---
  { id: 'bnl1', name: 'Untamed', park: 'Walibi Holland', country: 'Netherlands', type: CoasterType.Hybrid, manufacturer: 'RMC', imageUrl: 'https://picsum.photos/800/600?random=102' },
  { id: 'bnl2', name: 'Goliath', park: 'Walibi Holland', country: 'Netherlands', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=103' },
  { id: 'bnl3', name: 'Lost Gravity', park: 'Walibi Holland', country: 'Netherlands', type: CoasterType.Steel, manufacturer: 'Mack', imageUrl: 'https://picsum.photos/800/600?random=104' },
  { id: 'bnl4', name: 'Troy', park: 'Toverland', country: 'Netherlands', type: CoasterType.Wooden, manufacturer: 'GCI', imageUrl: 'https://picsum.photos/800/600?random=105' },
  { id: 'bnl5', name: 'Fénix', park: 'Toverland', country: 'Netherlands', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=106' },
  { id: 'bnl6', name: 'Baron 1898', park: 'Efteling', country: 'Netherlands', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=107' },
  { id: 'bnl7', name: 'Joris en de Draak', park: 'Efteling', country: 'Netherlands', type: CoasterType.Wooden, manufacturer: 'GCI', imageUrl: 'https://picsum.photos/800/600?random=108' },
  { id: 'bnl8', name: 'Kondaa', park: 'Walibi Belgium', country: 'Belgium', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=109' },
  { id: 'bnl9', name: 'Ride to Happiness', park: 'Plopsaland De Panne', country: 'Belgium', type: CoasterType.Steel, manufacturer: 'Mack', imageUrl: 'https://picsum.photos/800/600?random=110' },
  { id: 'fr1', name: 'Toutatis', park: 'Parc Astérix', country: 'France', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=111' },
  { id: 'fr2', name: 'OzIris', park: 'Parc Astérix', country: 'France', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=112' },
  { id: 'fr3', name: 'Tonnerre 2 Zeus', park: 'Parc Astérix', country: 'France', type: CoasterType.Wooden, manufacturer: 'GCI', imageUrl: 'https://picsum.photos/800/600?random=113' },
  
  // --- EUROPE: SCANDINAVIA ---
  { id: 'sc1', name: 'Wildfire', park: 'Kolmården', country: 'Sweden', type: CoasterType.Wooden, manufacturer: 'RMC', imageUrl: 'https://picsum.photos/800/600?random=114' },
  { id: 'sc2', name: 'Helix', park: 'Liseberg', country: 'Sweden', type: CoasterType.Steel, manufacturer: 'Mack', imageUrl: 'https://picsum.photos/800/600?random=115' },
  { id: 'sc3', name: 'Balder', park: 'Liseberg', country: 'Sweden', type: CoasterType.Wooden, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=116' },
  { id: 'sc4', name: 'Valkyria', park: 'Liseberg', country: 'Sweden', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=117' },
  { id: 'sc5', name: 'Taiga', park: 'Linnanmäki', country: 'Finland', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=118' },
  { id: 'sc6', name: 'Piraten', park: 'Djurs Sommerland', country: 'Denmark', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=119' },
  
  // --- EUROPE: SPAIN & ITALY ---
  { id: 'sp1', name: 'Shambhala', park: 'PortAventura', country: 'Spain', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=120' },
  { id: 'sp2', name: 'Dragon Khan', park: 'PortAventura', country: 'Spain', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=121' },
  { id: 'sp3', name: 'Red Force', park: 'Ferrari Land', country: 'Spain', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=122' },
  { id: 'sp4', name: 'Batman: Gotham City Escape', park: 'Parque Warner Madrid', country: 'Spain', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=123' },
  { id: 'sp5', name: 'Superman: La Atracción de Acero', park: 'Parque Warner Madrid', country: 'Spain', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=124' },
  { id: 'sp6', name: 'Stunt Fall', park: 'Parque Warner Madrid', country: 'Spain', type: CoasterType.Steel, manufacturer: 'Vekoma', imageUrl: 'https://picsum.photos/800/600?random=125' },
  { id: 'it1', name: 'iSpeed', park: 'Mirabilandia', country: 'Italy', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=126' },
  { id: 'it2', name: 'Katun', park: 'Mirabilandia', country: 'Italy', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=127' },
  { id: 'it3', name: 'Raptor', park: 'Gardaland', country: 'Italy', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=128' },
  
  // --- ASIA: JAPAN ---
  { id: 'jp1', name: 'Hakugei', park: 'Nagashima Spa Land', country: 'Japan', type: CoasterType.Hybrid, manufacturer: 'RMC', imageUrl: 'https://picsum.photos/800/600?random=129' },
  { id: 'jp2', name: 'Steel Dragon 2000', park: 'Nagashima Spa Land', country: 'Japan', type: CoasterType.Steel, manufacturer: 'Morgan', imageUrl: 'https://picsum.photos/800/600?random=130' },
  { id: 'jp3', name: 'Eejanaika', park: 'Fuji-Q Highland', country: 'Japan', type: CoasterType.Steel, manufacturer: 'S&S', imageUrl: 'https://picsum.photos/800/600?random=131' },
  { id: 'jp4', name: 'Takabisha', park: 'Fuji-Q Highland', country: 'Japan', type: CoasterType.Steel, manufacturer: 'Gerstlauer', imageUrl: 'https://picsum.photos/800/600?random=132' },
  { id: 'jp5', name: 'Fujiyama', park: 'Fuji-Q Highland', country: 'Japan', type: CoasterType.Steel, manufacturer: 'Togo', imageUrl: 'https://picsum.photos/800/600?random=133' },
  { id: 'jp6', name: 'Thunder Dolphin', park: 'Tokyo Dome City', country: 'Japan', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=134' },
  { id: 'jp7', name: 'Flying Dinosaur', park: 'Universal Studios Japan', country: 'Japan', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=135' },
  
  // --- ASIA: CHINA & SOUTH KOREA ---
  { id: 'as1', name: 'T-Express', park: 'Everland', country: 'South Korea', type: CoasterType.Wooden, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=136' },
  { id: 'as2', name: 'Wood Coaster', park: 'Knight Valley', country: 'China', type: CoasterType.Wooden, manufacturer: 'GCI', imageUrl: 'https://picsum.photos/800/600?random=137' },
  { id: 'as3', name: 'Dinoconda', park: 'China Dinosaurs Park', country: 'China', type: CoasterType.Steel, manufacturer: 'S&S', imageUrl: 'https://picsum.photos/800/600?random=138' },
  { id: 'as4', name: 'Coaster Through the Clouds', park: 'Nanchang Sunac Land', country: 'China', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=139' },
  { id: 'as5', name: 'Soaring with Dragon', park: 'Hefei Sunac Land', country: 'China', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=140' },
  
  // --- OCEANIA & MIDDLE EAST ---
  { id: 'oc1', name: 'DC Rivals HyperCoaster', park: 'Warner Bros. Movie World', country: 'Australia', type: CoasterType.Steel, manufacturer: 'Mack', imageUrl: 'https://picsum.photos/800/600?random=141' },
  { id: 'oc2', name: 'Superman Escape', park: 'Warner Bros. Movie World', country: 'Australia', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=142' },
  { id: 'oc3', name: 'Steel Taipan', park: 'Dreamworld', country: 'Australia', type: CoasterType.Steel, manufacturer: 'Mack', imageUrl: 'https://picsum.photos/800/600?random=143' },
  { id: 'me1', name: 'Formula Rossa', park: 'Ferrari World Abu Dhabi', country: 'UAE', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=144' },
  { id: 'me2', name: 'Flying Aces', park: 'Ferrari World Abu Dhabi', country: 'UAE', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=145' },
  
  // --- MORE USA ---
  { id: 'usa40', name: 'Banshee', park: 'Kings Island', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=146' },
  { id: 'usa41', name: 'Afterburn', park: 'Carowinds', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=147' },
  { id: 'usa42', name: 'Alpengeist', park: 'Busch Gardens Williamsburg', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=148' },
  { id: 'usa43', name: 'Renegade', park: 'Valleyfair', country: 'USA', type: CoasterType.Wooden, manufacturer: 'GCI', imageUrl: 'https://picsum.photos/800/600?random=149' },
  { id: 'usa44', name: 'Prowler', park: 'Worlds of Fun', country: 'USA', type: CoasterType.Wooden, manufacturer: 'GCI', imageUrl: 'https://picsum.photos/800/600?random=150' },
  { id: 'usa45', name: 'Mamba', park: 'Worlds of Fun', country: 'USA', type: CoasterType.Steel, manufacturer: 'Morgan', imageUrl: 'https://picsum.photos/800/600?random=151' },
  { id: 'usa46', name: 'Steel Eel', park: 'SeaWorld San Antonio', country: 'USA', type: CoasterType.Steel, manufacturer: 'Morgan', imageUrl: 'https://picsum.photos/800/600?random=152' },
  { id: 'usa47', name: 'New Texas Giant', park: 'Six Flags Over Texas', country: 'USA', type: CoasterType.Hybrid, manufacturer: 'RMC', imageUrl: 'https://picsum.photos/800/600?random=153' },
  { id: 'usa48', name: 'Titan', park: 'Six Flags Over Texas', country: 'USA', type: CoasterType.Steel, manufacturer: 'Giovanola', imageUrl: 'https://picsum.photos/800/600?random=154' },
  { id: 'usa49', name: 'Shock Wave', park: 'Six Flags Over Texas', country: 'USA', type: CoasterType.Steel, manufacturer: 'Schwarzkopf', imageUrl: 'https://picsum.photos/800/600?random=155' },
  { id: 'usa50', name: 'Boardwalk Bullet', park: 'Kemah Boardwalk', country: 'USA', type: CoasterType.Wooden, manufacturer: 'Gravity Group', imageUrl: 'https://picsum.photos/800/600?random=156' },
  { id: 'usa51', name: 'Switchback', park: 'ZDT\'s Amusement Park', country: 'USA', type: CoasterType.Wooden, manufacturer: 'Gravity Group', imageUrl: 'https://picsum.photos/800/600?random=157' },
  { id: 'usa52', name: 'Ravine Flyer II', park: 'Waldameer', country: 'USA', type: CoasterType.Wooden, manufacturer: 'Gravity Group', imageUrl: 'https://picsum.photos/800/600?random=158' },
  { id: 'usa53', name: 'Hades 360', park: 'Mt. Olympus', country: 'USA', type: CoasterType.Wooden, manufacturer: 'Gravity Group', imageUrl: 'https://picsum.photos/800/600?random=159' },
  { id: 'usa54', name: 'Zeus', park: 'Mt. Olympus', country: 'USA', type: CoasterType.Wooden, manufacturer: 'CCI', imageUrl: 'https://picsum.photos/800/600?random=160' },
  { id: 'usa55', name: 'Cyclops', park: 'Mt. Olympus', country: 'USA', type: CoasterType.Wooden, manufacturer: 'CCI', imageUrl: 'https://picsum.photos/800/600?random=161' },
  { id: 'usa56', name: 'Cornball Express', park: 'Indiana Beach', country: 'USA', type: CoasterType.Wooden, manufacturer: 'CCI', imageUrl: 'https://picsum.photos/800/600?random=162' },
  { id: 'usa57', name: 'Steel Hawg', park: 'Indiana Beach', country: 'USA', type: CoasterType.Steel, manufacturer: 'S&S', imageUrl: 'https://picsum.photos/800/600?random=163' },
  { id: 'usa58', name: 'Lost Coaster of Superstition Mountain', park: 'Indiana Beach', country: 'USA', type: CoasterType.Wooden, manufacturer: 'CCI', imageUrl: 'https://picsum.photos/800/600?random=164' },
  { id: 'usa59', name: 'Shivering Timbers', park: 'Michigan\'s Adventure', country: 'USA', type: CoasterType.Wooden, manufacturer: 'CCI', imageUrl: 'https://picsum.photos/800/600?random=165' },
  { id: 'usa60', name: 'Jack Rabbit', park: 'Kennywood', country: 'USA', type: CoasterType.Wooden, manufacturer: 'Miller', imageUrl: 'https://picsum.photos/800/600?random=166' },
  { id: 'usa61', name: 'Thunderbolt', park: 'Kennywood', country: 'USA', type: CoasterType.Wooden, manufacturer: 'Andy Vettel', imageUrl: 'https://picsum.photos/800/600?random=167' },
  { id: 'usa62', name: 'Racer', park: 'Kennywood', country: 'USA', type: CoasterType.Wooden, manufacturer: 'Miller', imageUrl: 'https://picsum.photos/800/600?random=168' },
  { id: 'usa63', name: 'Comet', park: 'Hersheypark', country: 'USA', type: CoasterType.Wooden, manufacturer: 'PTC', imageUrl: 'https://picsum.photos/800/600?random=169' },
  { id: 'usa64', name: 'Great Bear', park: 'Hersheypark', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=170' },
  { id: 'usa65', name: 'Storm Runner', park: 'Hersheypark', country: 'USA', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=171' },
  { id: 'usa66', name: 'Fahrenheit', park: 'Hersheypark', country: 'USA', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=172' },
  { id: 'usa67', name: 'Twister', park: 'Knoebels', country: 'USA', type: CoasterType.Wooden, manufacturer: 'Fetterman', imageUrl: 'https://picsum.photos/800/600?random=173' },
  { id: 'usa68', name: 'Flying Turns', park: 'Knoebels', country: 'USA', type: CoasterType.Bobsled, manufacturer: 'Knoebels', imageUrl: 'https://picsum.photos/800/600?random=174' },
  { id: 'usa69', name: 'Impulse', park: 'Knoebels', country: 'USA', type: CoasterType.Steel, manufacturer: 'Zierer', imageUrl: 'https://picsum.photos/800/600?random=175' },
  { id: 'usa70', name: 'Talon', park: 'Dorney Park', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=176' },
  { id: 'usa71', name: 'Steel Force', park: 'Dorney Park', country: 'USA', type: CoasterType.Steel, manufacturer: 'Morgan', imageUrl: 'https://picsum.photos/800/600?random=177' },
  { id: 'usa72', name: 'Hydra the Revenge', park: 'Dorney Park', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=178' },
  { id: 'usa73', name: 'Possessed', park: 'Dorney Park', country: 'USA', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=179' },
  { id: 'usa74', name: 'Medusa', park: 'Six Flags Great Adventure', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=180' },
  { id: 'usa75', name: 'Batman The Ride', park: 'Six Flags Great Adventure', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=181' },
  { id: 'usa76', name: 'Superman: Ultimate Flight', park: 'Six Flags Great Adventure', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=182' },
  { id: 'usa77', name: 'Green Lantern', park: 'Six Flags Great Adventure', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=183' },
  { id: 'usa78', name: 'Joker', park: 'Six Flags Great Adventure', country: 'USA', type: CoasterType.Steel, manufacturer: 'S&S', imageUrl: 'https://picsum.photos/800/600?random=184' },
  { id: 'usa79', name: 'Boulder Dash', park: 'Lake Compounce', country: 'USA', type: CoasterType.Wooden, manufacturer: 'CCI', imageUrl: 'https://picsum.photos/800/600?random=185' },
  { id: 'usa80', name: 'Phobia Phear Coaster', park: 'Lake Compounce', country: 'USA', type: CoasterType.Steel, manufacturer: 'Premier Rides', imageUrl: 'https://picsum.photos/800/600?random=186' },
  { id: 'usa81', name: 'Superman The Ride', park: 'Six Flags New England', country: 'USA', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=187' },
  { id: 'usa82', name: 'Batman The Dark Knight', park: 'Six Flags New England', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=188' },
  { id: 'usa83', name: 'Untamed', park: 'Canobie Lake Park', country: 'USA', type: CoasterType.Steel, manufacturer: 'Gerstlauer', imageUrl: 'https://picsum.photos/800/600?random=189' },
  { id: 'usa84', name: 'Yankee Cannonball', park: 'Canobie Lake Park', country: 'USA', type: CoasterType.Wooden, manufacturer: 'PTC', imageUrl: 'https://picsum.photos/800/600?random=190' },
  { id: 'usa85', name: 'Excalibur', park: 'Funtown Splashtown USA', country: 'USA', type: CoasterType.Wooden, manufacturer: 'CCI', imageUrl: 'https://picsum.photos/800/600?random=191' },
  { id: 'usa86', name: 'Goliath', park: 'La Ronde', country: 'Canada', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=192' },
  { id: 'usa87', name: 'Vampire', park: 'La Ronde', country: 'Canada', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=193' },
  { id: 'usa88', name: 'Monster', park: 'La Ronde', country: 'Canada', type: CoasterType.Wooden, manufacturer: 'Martin & Vleminckx', imageUrl: 'https://picsum.photos/800/600?random=194' },
  { id: 'usa89', name: 'Mindbender', park: 'Galaxyland', country: 'Canada', type: CoasterType.Steel, manufacturer: 'Schwarzkopf', imageUrl: 'https://picsum.photos/800/600?random=195' },
  { id: 'usa90', name: 'Coaster', park: 'Playland', country: 'Canada', type: CoasterType.Wooden, manufacturer: 'Phare', imageUrl: 'https://picsum.photos/800/600?random=196' },
  { id: 'usa91', name: 'Silver Bullet', park: 'Knott\'s Berry Farm', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=197' },
  { id: 'usa92', name: 'HangTime', park: 'Knott\'s Berry Farm', country: 'USA', type: CoasterType.Steel, manufacturer: 'Gerstlauer', imageUrl: 'https://picsum.photos/800/600?random=198' },
  { id: 'usa93', name: 'Montezooma\'s Revenge', park: 'Knott\'s Berry Farm', country: 'USA', type: CoasterType.Steel, manufacturer: 'Schwarzkopf', imageUrl: 'https://picsum.photos/800/600?random=199' },
  { id: 'usa94', name: 'Incredicoaster', park: 'Disney California Adventure', country: 'USA', type: CoasterType.Steel, manufacturer: 'Intamin', imageUrl: 'https://picsum.photos/800/600?random=200' },
  { id: 'usa95', name: 'Matterhorn Bobsleds', park: 'Disneyland', country: 'USA', type: CoasterType.Steel, manufacturer: 'Arrow', imageUrl: 'https://picsum.photos/800/600?random=201' },
  { id: 'usa96', name: 'Space Mountain', park: 'Disneyland', country: 'USA', type: CoasterType.Steel, manufacturer: 'Walt Disney Imagineering', imageUrl: 'https://picsum.photos/800/600?random=202' },
  { id: 'usa97', name: 'Big Thunder Mountain Railroad', park: 'Disneyland', country: 'USA', type: CoasterType.Steel, manufacturer: 'Walt Disney Imagineering', imageUrl: 'https://picsum.photos/800/600?random=203' },
  { id: 'usa98', name: 'Emperor', park: 'SeaWorld San Diego', country: 'USA', type: CoasterType.Steel, manufacturer: 'B&M', imageUrl: 'https://picsum.photos/800/600?random=204' },
  { id: 'usa99', name: 'Electric Eel', park: 'SeaWorld San Diego', country: 'USA', type: CoasterType.Steel, manufacturer: 'Premier Rides', imageUrl: 'https://picsum.photos/800/600?random=205' },
  { id: 'usa100', name: 'Manta', park: 'SeaWorld San Diego', country: 'USA', type: CoasterType.Steel, manufacturer: 'Mack', imageUrl: 'https://picsum.photos/800/600?random=206' }
];

export const INITIAL_USERS: User[] = [
  { id: 'u1', name: 'Main Rider', avatarColor: 'bg-primary' },
];

export const COASTER_TYPES = Object.values(CoasterType);